//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCalculator.Ressources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleCalculator.Ressources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to   + or 'add' or 'plus' for addition.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to   + or 'add' or 'plus' for addition.
        /// </summary>
        internal static string AdditionHelp {
            get {
                return ResourceManager.GetString("AdditionHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to divide.
        /// </summary>
        internal static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to divided.
        /// </summary>
        internal static string Divided {
            get {
                return ResourceManager.GetString("Divided", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to   / or 'divide' or 'divided' for division.
        /// </summary>
        internal static string DivisionHelp {
            get {
                return ResourceManager.GetString("DivisionHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the first number: .
        /// </summary>
        internal static string EnterFirstNumber {
            get {
                return ResourceManager.GetString("EnterFirstNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the operation (+, -, *, /): .
        /// </summary>
        internal static string EnterOperation {
            get {
                return ResourceManager.GetString("EnterOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the second number: .
        /// </summary>
        internal static string EnterSecondNumber {
            get {
                return ResourceManager.GetString("EnterSecondNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid input. Please enter a valid number..
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid operation entered..
        /// </summary>
        internal static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to minus.
        /// </summary>
        internal static string Minus {
            get {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to   * or 'multiply' or 'times' for multiplication.
        /// </summary>
        internal static string MultiplicationHelp {
            get {
                return ResourceManager.GetString("MultiplicationHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to multiply.
        /// </summary>
        internal static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to plus.
        /// </summary>
        internal static string Plus {
            get {
                return ResourceManager.GetString("Plus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Result: {0}.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value {0:F2} {1} the value {2:F2} is equal to {3:F2}. .
        /// </summary>
        internal static string ResultFormat {
            get {
                return ResourceManager.GetString("ResultFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select language (1=English, 2=French): .
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to subtract.
        /// </summary>
        internal static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to   - or 'minus' or 'subtract' for subtraction.
        /// </summary>
        internal static string SubtractionHelp {
            get {
                return ResourceManager.GetString("SubtractionHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please try again..
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valid operations are:.
        /// </summary>
        internal static string ValidOperations {
            get {
                return ResourceManager.GetString("ValidOperations", resourceCulture);
            }
        }
    }
}